const {test}=require('node:test');const assert=require('node:assert/strict');const jwt=require('jsonwebtoken');
const {createAuth,passwordVersion,readiness}=require('../backend/lib/security.cjs');
const {recordPage}=require('../backend/lib/pagination.cjs');
const {processOutbox}=require('../backend/lib/operations.cjs');
const secret='isolated-test-secret';
function requestToken(hash='old'){return jwt.sign({id:'1',email:'admin@example.invalid',pv:passwordVersion(hash),jti:'unique-session'},secret,{expiresIn:'1h'});}
async function authorize(token,password='old',revoked=false){let passed=false;const response={statusCode:200,status(code){this.statusCode=code;return this;},json(body){this.body=body;}};const pool={query:async sql=>[sql.startsWith('SELECT password')?[{password}]:revoked?[{tokenId:'unique-session'}]:[]]};await createAuth(()=>pool,secret)({headers:{authorization:'Bearer '+token}},response,()=>passed=true);return {...response,passed};}
test('password changes and server logout invalidate existing sessions',async()=>{assert.equal((await authorize(requestToken())).passed,true);assert.equal((await authorize(requestToken(),'new')).statusCode,401);assert.equal((await authorize(requestToken(),'old',true)).statusCode,401);assert.equal((await authorize(requestToken('new'),'new')).passed,true);});
test('legacy or forged tokens are denied',async()=>{assert.equal((await authorize(jwt.sign({id:'1',email:'a'},secret))).statusCode,401);assert.equal((await authorize('forged')).statusCode,401);});
test('readiness reflects dependency failures, not just startup state',async()=>{assert.equal(await readiness(null,false),false);assert.equal(await readiness({query:async()=>[[]]},true),true);assert.equal(await readiness({query:async()=>{throw Error('offline');}},true),false);});
test('pagination is bounded and cursor values are parameterized',async()=>{let call;const rows=Array.from({length:101},(_,i)=>({id:String(i),createdAt:'2026-01-01'}));const pool={query:async(sql,args)=>{call={sql,args};return[rows];}};const page=await recordPage(pool,'inquiries');assert.equal(page.items.length,100);assert.ok(page.nextCursor);await recordPage(pool,'inquiries',{cursor:page.nextCursor});assert.match(call.sql,/createdAt < \?/);assert.equal(call.args.at(-1),101);await assert.rejects(recordPage(pool,'inquiries',{cursor:'bad'}),/Invalid page cursor/);});
test('outbox records send success with a stable provider idempotency key',async()=>{const calls=[];const row={id:'mail1',payload:JSON.stringify({to:'x@example.invalid',idempotencyKey:'mail1'}),attempts:0};const connection={beginTransaction:async()=>{},commit:async()=>{},rollback:async()=>{},release(){},query:async(sql,args)=>{calls.push({sql,args});return sql.startsWith('SELECT')?[[row]]:[{}];}};const pool={getConnection:async()=>connection,query:connection.query};let payload;await processOutbox(pool,async data=>{payload=data;return{sent:true,messageId:'provider-id'};});assert.equal(payload.idempotencyKey,'mail1');assert.match(calls.at(-1).sql,/status='sent'/);assert.equal(calls.at(-1).args[0],'provider-id');});
test('outbox persists a retry and eventually surfaces permanent failure',async()=>{for(const attempts of [0,5]){let update;const row={id:'mail1',payload:{},attempts};const connection={beginTransaction:async()=>{},commit:async()=>{},rollback:async()=>{},release(){},query:async sql=>sql.startsWith('SELECT')?[[row]]:[{}]};await processOutbox({getConnection:async()=>connection,query:async(sql,args)=>update={sql,args}},async()=>({sent:false,reason:'provider unavailable'}));assert.equal(update.args[0],attempts===5?'failed':'pending');assert.ok(update.args[2]>0);}});
